name: Add to Project

on:
  #pull_request_target:
  #pull_request:
  #  types:
  #    - opened
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to formulation project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/NOAA-OWP/projects/30 
          github-token: ${{ secrets.TEST-CFE-2 }}
