# Test ngen integration

name: Ngen Integration Tests

# Controls when the action will run.
on:
  push:
    branches: [ master, dev, notreal ]
  pull_request:
    branches: [ master, dev, notreal ]
  workflow_dispatch:

env:
  # Obtained from https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  # TODO: add something later that can check the runners for hyperthreading
  LINUX_NUM_PROC_CORES: 2
  MACOS_NUM_PROC_CORES: 3
  ASAN_OPTIONS: detect_leaks=false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run general unit tests in linux environment
  test_surfacebmi_plus_cfe:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout actions in another repo
        uses: actions/checkout@v3
        with:
          repository: noaa-owp/ngen
          path: .github/actions/ngen-build

        #- uses: ./.github/actions/ngen-build/action.yaml

      - name: Build Ngen
        #uses: NOAA-OWP/ngen/.github/actions/ngen-build/action.yaml@master
        uses: ./.github/actions/ngen-build/action.yaml
        with:
          targets: "ngen"
          build-cores: ${{ env.LINUX_NUM_PROC_CORES }}
          #is this required for this test?
          bmi_c: 'ON'
          bmi_fortran: 'ON'
        timeout-minutes: 15

      - name: Run surfacebmi plus cfebmi
        run: |
          echo "end of ngen_integration testing"
      #    inputfile='realizations/realization_cfe_pet.json'
      #    ./cmake_build/ngen ../../data/catchment_data.geojson "cat-27" ../../data/nexus_data.geojson "nex-26" $inputfile
